#!/usr/bin/env python3
"""Generate PR-safe dispatcher coverage documentation."""

from __future__ import annotations

import pathlib
import re
import sys

try:
    import yaml
except Exception:
    print("::error title=Missing PyYAML::Install PyYAML before running this script.")
    sys.exit(1)

WF_DIR = pathlib.Path(".github/workflows")
DOCS = pathlib.Path(".github/docs")
STATUS_MD = DOCS / "PR_SAFE_STATUS.md"
README = pathlib.Path("README.md")
START = "<!-- pr-safe-status:start -->"
END = "<!-- pr-safe-status:end -->"
TARGET = "./.github/actions/pr-safe-dispatch"


def scan() -> list[tuple[str, str]]:
    rows: list[tuple[str, str]] = []
    if not WF_DIR.exists():
        return rows
    for workflow in sorted(WF_DIR.glob("*.y*ml")):
        try:
            data = yaml.safe_load(workflow.read_text(encoding="utf-8"))
        except Exception:
            rows.append((workflow.name, "parse-failed"))
            continue
        found_any = False
        jobs = (data or {}).get("jobs") or {}
        for job_name, job in jobs.items():
            steps = (job or {}).get("steps") or []
            present = any(
                isinstance(step, dict)
                and str(step.get("uses", "")).strip() == TARGET
                for step in steps
            )
            if present:
                found_any = True
                rows.append((f"{workflow.name} » {job_name}", "present"))
        if not found_any:
            rows.append((workflow.name, "not-inserted"))
    return rows


def render_table(rows: list[tuple[str, str]]) -> str:
    if not rows:
        return "_No workflows found._"
    lines = ["| Workflow / Job | PR-safe dispatcher |", "|---|---|"]
    lines.extend(f"| `{name}` | {state} |" for name, state in rows)
    return "\n".join(lines)


def write_if_changed(path: pathlib.Path, content: str) -> bool:
    old = path.read_text(encoding="utf-8") if path.exists() else ""
    if old.strip() == content.strip():
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def update_readme(block_md: str) -> bool:
    if not README.exists():
        text = (
            f"# {pathlib.Path.cwd().name}\n\n"
            f"## CI Coverage\n\n{START}\n{block_md}\n{END}\n"
        )
        return write_if_changed(README, text)

    text = README.read_text(encoding="utf-8")
    if START in text and END in text:
        updated = re.sub(
            rf"{re.escape(START)}.*?{re.escape(END)}",
            f"{START}\n{block_md}\n{END}",
            text,
            flags=re.S,
        )
    else:
        updated = text.rstrip() + f"\n\n## CI Coverage\n\n{START}\n{block_md}\n{END}\n"

    if updated == text:
        return False
    README.write_text(updated, encoding="utf-8")
    return True


def main() -> int:
    DOCS.mkdir(parents=True, exist_ok=True)
    table = render_table(scan())
    status_changed = write_if_changed(
        STATUS_MD,
        f"# PR-safe Dispatcher Coverage\n\n{table}\n",
    )
    readme_changed = update_readme(
        f"_This table is auto-generated by AutoDocs._\n\n{table}"
    )
    print("Updated AutoDocs outputs." if status_changed or readme_changed else "No AutoDocs changes.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
